// Bairros com página própria. O slug vai na URL (sem acento); o nome aparece no texto.
export const bairros = [
  {
    slug: "curitiba",
    bairros: [
      { slug: "agua-verde", nome: "Água Verde" },
      { slug: "ahu", nome: "Ahú" },
      { slug: "alto-boqueirao", nome: "Alto Boqueirão" },
      { slug: "alto-da-gloria", nome: "Alto da Glória" },
      { slug: "alto-da-xv", nome: "Alto da XV" },
      { slug: "bacacheri", nome: "Bacacheri" },
      { slug: "bairro-alto", nome: "Bairro Alto" },
      { slug: "barreirinha", nome: "Barreirinha" },
      { slug: "batel", nome: "Batel" },
      { slug: "bigorrilho", nome: "Bigorrilho" },
      { slug: "boa-vista", nome: "Boa Vista" },
      { slug: "bom-retiro", nome: "Bom Retiro" },
      { slug: "boqueirao", nome: "Boqueirão" },
      { slug: "cabral", nome: "Cabral" },
      { slug: "cajuru", nome: "Cajuru" },
      { slug: "capao-da-imbuia", nome: "Capão da Imbuia" },
      { slug: "capao-raso", nome: "Capão Raso" },
      { slug: "cascatinha", nome: "Cascatinha" },
      { slug: "centro", nome: "Centro" },
      { slug: "centro-civico", nome: "Centro Cívico" },
      { slug: "cidade-industrial", nome: "Cidade Industrial" },
      { slug: "cristal", nome: "Cristal" },
      { slug: "fazendinha", nome: "Fazendinha" },
      { slug: "fanny", nome: "Fanny" },
      { slug: "ganchinho", nome: "Ganchinho" },
      { slug: "guabirotuba", nome: "Guabirotuba" },
      { slug: "hauer", nome: "Hauer" },
      { slug: "hugo-lange", nome: "Hugo Lange" },
      { slug: "jardim-botanico", nome: "Jardim Botânico" },
      { slug: "jardim-das-americas", nome: "Jardim das Américas" },
      { slug: "jardim-social", nome: "Jardim Social" },
      { slug: "juveve", nome: "Juvevê" },
      { slug: "lindoia", nome: "Lindóia" },
      { slug: "merces", nome: "Mercês" },
      { slug: "mossungue", nome: "Mossunguê" },
      { slug: "novo-mundo", nome: "Novo Mundo" },
      { slug: "orleans", nome: "Orleans" },
      { slug: "parolin", nome: "Parolin" },
      { slug: "pilarzinho", nome: "Pilarzinho" },
      { slug: "pinheirinho", nome: "Pinheirinho" },
      { slug: "portao", nome: "Portão" },
      { slug: "reboucas", nome: "Rebouças" },
      { slug: "santa-candida", nome: "Santa Cândida" },
      { slug: "santa-felicidade", nome: "Santa Felicidade" },
      { slug: "santa-quiteria", nome: "Santa Quitéria" },
      { slug: "seminario", nome: "Seminário" },
      { slug: "sitio-cercado", nome: "Sítio Cercado" },
      { slug: "taruma", nome: "Tarumã" },
      { slug: "tatuquara", nome: "Tatuquara" },
      { slug: "tingui", nome: "Tingui" },
      { slug: "uberaba", nome: "Uberaba" },
      { slug: "umbara", nome: "Umbará" },
      { slug: "vila-izabel", nome: "Vila Izabel" },
      { slug: "vista-alegre", nome: "Vista Alegre" },
    ],
  },
]
