export const bairros = [
  {
    slug: "curitiba",
    bairros: [
      { slug: "abatia" },
      { slug: "agua-verde" },
      { slug: "ahú" },
      { slug: "alto-boqueirao" },
      { slug: "alto-da-gloria" },
      { slug: "alto-da-xv" },
      { slug: "bacacheri" },
      { slug: "bairro-alto" },
      { slug: "barreirinha" },
      { slug: "batel" },
      { slug: "bigorrilho" },
      { slug: "boa-vista" },
      { slug: "bom-retiro" },
      { slug: "boqueirao" },
      { slug: "cabral" },
      { slug: "cajuru" },
      { slug: "capao-da-imbuia" },
      { slug: "capao-raso" },
      { slug: "cascatinha" },
      { slug: "centro" },
      { slug: "centro-civico" },
      { slug: "cidade-industrial" },
      { slug: "cristal" },
      { slug: "fazendinha" },
      { slug: "fanny" },
      { slug: "ganchinho" },
      { slug: "guabirotuba" },
      { slug: "hauer" },
      { slug: "hugo-lange" },
      { slug: "jardim-botanico" },
      { slug: "jardim-das-americas" },
      { slug: "jardim-social" },
      { slug: "juveve" },
      { slug: "lindoia" },
      { slug: "mercês" },
      { slug: "mossungue" },
      { slug: "novo-mundo" },
      { slug: "orleans" },
      { slug: "parolin" },
      { slug: "pilarzinho" },
      { slug: "pinheirinho" },
      { slug: "portao" },
      { slug: "reboucas" },
      { slug: "santa-candida" },
      { slug: "santa-felicidade" },
      { slug: "santa-quiteria" },
      { slug: "seminario" },
      { slug: "sitio-cercado" },
      { slug: "taruma" },
      { slug: "tatuquara" },
      { slug: "tingui" },
      { slug: "uberaba" },
      { slug: "umbara" },
      { slug: "vila-izabel" },
      { slug: "vista-alegre" }
    ]
  }
]